version: '0.1'

services:
  web:
    build: ./
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8080:8080
    env_file:
      - ./.env.dev
    links:
      - db:db

  db:
    image:
      postgres:14.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=psg_user
      - POSTGRES_PASSWORD=lkmjgferM4_
      - POSTGRES_DB=psg_django_db


volumes:
  postgres_data:
